"""
neuros.templates
================
One-Click Robot Templates — Phase 1, Component #7.

Pre-built robot project templates that work out of the box.
Users run `neuros new my_robot --template <name>` and get a working robot.

Available templates (Phase 1 — 10 total):
  1. blinker           — LED blink (hello world of robotics)
  2. line-follower     — Follow a line using IR sensors
  3. obstacle-avoider  — Dodge obstacles with ultrasonic sensor
  4. wheeled-bot       — Basic 2-wheel differential drive
  5. servo-sweep       — Sweep a servo motor back and forth
  6. motor-test        — Test DC motor control with acceleration
  7. sensor-reader     — Read and log multiple sensor values
  8. remote-control    — Control robot via keyboard/WebSocket
  9. light-follower    — Follow a light source using LDRs
  10. node-example     — Custom Node class with lifecycle hooks
"""

from __future__ import annotations
from typing import Dict

# ── Template definitions ──────────────────────────────────────────────────

TEMPLATES: Dict[str, dict] = {}


def _t(name: str, title: str, description: str, code: str, config: str = ""):
    """Register a template."""
    TEMPLATES[name] = {
        "name": name,
        "title": title,
        "description": description,
        "code": code,
        "config": config,
    }


# ── 1. Blinker ─────────────────────────────────────────────────────────────
_t("blinker", "LED Blinker", "Hello World of robotics — blink an LED", '''
"""
{project_name} — LED Blinker
Generated by: neuros new {project_name} --template blinker
Hardware: Any board with an LED (Arduino pin 13, ESP32 pin 2, Pi pin 17)
"""
from neuros import Robot, spin

robot = Robot("{project_name}")
robot.start()

# Configure the LED pin (change pin number for your board)
robot.pin("LED", pin=13, mode="output")

# Blink at 1 Hz (once per second)
@robot.every(hz=1)
def blink():
    robot.toggle("LED")
    robot.publish("status/led", {{"state": "toggle"}})

print("🟢 LED blinker running — Ctrl+C to stop")
spin(robot)
''')


# ── 2. Line Follower ──────────────────────────────────────────────────────
_t("line-follower", "Line Follower", "Follow a line using IR sensors + PID control", '''
"""
{project_name} — Line Follower Robot
Generated by: neuros new {project_name} --template line-follower

Hardware required:
  - 2x DC motors (left/right)
  - 2x IR line sensors (analog)
  - Motor driver (L298N or similar)
"""
from neuros import Robot, Node, spin, NodePriority


class LineFollowerNode(Node):
    """PID-based line following with 2 IR sensors."""

    def configure(self):
        # IR sensors (analog input)
        self.hal.pin("IR_LEFT",  board_pin=2, mode="analog_in")
        self.hal.pin("IR_RIGHT", board_pin=3, mode="analog_in")

        # Motors (PWM output)
        self.hal.pin("MOTOR_L", board_pin=5, mode="pwm")
        self.hal.pin("MOTOR_R", board_pin=6, mode="pwm")

        # PID gains
        self.kp = 1.0
        self.ki = 0.05
        self.kd = 0.3
        self.integral = 0.0
        self.prev_error = 0.0
        self.base_speed = 0.5

    def tick(self):
        left = self.hal.read("IR_LEFT")
        right = self.hal.read("IR_RIGHT")

        # Error: positive = drifting right, negative = drifting left
        error = left - right

        # PID calculation
        self.integral += error * (1.0 / self.hz)
        derivative = (error - self.prev_error) * self.hz
        correction = self.kp * error + self.ki * self.integral + self.kd * derivative
        self.prev_error = error

        # Apply to motors
        left_speed  = max(0, min(1, self.base_speed - correction))
        right_speed = max(0, min(1, self.base_speed + correction))

        self.hal.write("MOTOR_L", left_speed)
        self.hal.write("MOTOR_R", right_speed)

        self.publish("/robot/line", {{
            "ir_left": round(left, 3),
            "ir_right": round(right, 3),
            "error": round(error, 3),
            "correction": round(correction, 3),
        }})

    def on_emergency_stop(self, reason):
        self.hal.write("MOTOR_L", 0)
        self.hal.write("MOTOR_R", 0)
        super().on_emergency_stop(reason)


robot = Robot("{project_name}")
robot.add_node(LineFollowerNode("line_follower", hz=50, priority=NodePriority.HIGH))
robot.start()

print("🏁 Line follower running — place robot on the line")
spin(robot)
''')


# ── 3. Obstacle Avoider ───────────────────────────────────────────────────
_t("obstacle-avoider", "Obstacle Avoider", "Navigate around obstacles using ultrasonic sensor", '''
"""
{project_name} — Obstacle Avoider
Generated by: neuros new {project_name} --template obstacle-avoider

Hardware required:
  - HC-SR04 ultrasonic sensor (TRIG + ECHO pins)
  - 2x DC motors with motor driver
  - Optional: servo for scanning
"""
from neuros import Robot, Node, spin, NodePriority
import time
import random


class UltrasonicNode(Node):
    """Read distance from HC-SR04 ultrasonic sensor."""

    def configure(self):
        self.hal.pin("TRIG", board_pin=9,  mode="output")
        self.hal.pin("ECHO", board_pin=10, mode="input")
        self.distance = 100.0  # cm

    def tick(self):
        # Trigger pulse
        self.hal.write("TRIG", 0)
        time.sleep(0.000002)
        self.hal.write("TRIG", 1)
        time.sleep(0.00001)
        self.hal.write("TRIG", 0)

        # In a real implementation, we'd time the echo pulse
        # For simulator, use injected sensor value
        raw = self.hal.read("ECHO")
        self.distance = raw * 400  # scale to cm

        self.publish("/robot/sensor/distance", {{
            "cm": round(self.distance, 1),
        }})


class NavigatorNode(Node):
    """Obstacle avoidance logic."""

    def configure(self):
        self.hal.pin("MOTOR_L", board_pin=5, mode="pwm")
        self.hal.pin("MOTOR_R", board_pin=6, mode="pwm")
        self.distance = 100.0
        self.state = "forward"

        self.subscribe("/robot/sensor/distance", self.on_distance)

    def on_distance(self, msg):
        self.distance = msg.data.get("cm", 100.0)

    def tick(self):
        if self.distance < 20:
            # Too close — back up and turn
            self.state = "avoiding"
            self.hal.write("MOTOR_L", 0)
            self.hal.write("MOTOR_R", 0)
            time.sleep(0.2)

            # Turn randomly left or right
            if random.random() > 0.5:
                self.hal.write("MOTOR_L", 0.0)
                self.hal.write("MOTOR_R", 0.5)
            else:
                self.hal.write("MOTOR_L", 0.5)
                self.hal.write("MOTOR_R", 0.0)
        else:
            self.state = "forward"
            self.hal.write("MOTOR_L", 0.5)
            self.hal.write("MOTOR_R", 0.5)

        self.publish("/robot/nav", {{"state": self.state, "distance": self.distance}})

    def on_emergency_stop(self, reason):
        self.hal.write("MOTOR_L", 0)
        self.hal.write("MOTOR_R", 0)
        super().on_emergency_stop(reason)


robot = Robot("{project_name}")
robot.add_node(UltrasonicNode("sonar", hz=10))
robot.add_node(NavigatorNode("navigator", hz=5, priority=NodePriority.HIGH))
robot.start()

print("🤖 Obstacle avoider running — place objects in front of robot")
spin(robot)
''')


# ── 4. Wheeled Bot ─────────────────────────────────────────────────────────
_t("wheeled-bot", "Wheeled Bot", "Basic 2-wheel differential drive robot", '''
"""
{project_name} — Wheeled Bot (Differential Drive)
Generated by: neuros new {project_name} --template wheeled-bot

Hardware required:
  - 2x DC motors + wheels
  - L298N motor driver
  - Battery pack
"""
from neuros import Robot, Node, spin, NodePriority


class DriveNode(Node):
    """Differential drive motor controller."""

    def configure(self):
        # Motor pins (PWM)
        self.hal.pin("LEFT_FWD",  board_pin=5, mode="pwm")
        self.hal.pin("LEFT_BWD",  board_pin=6, mode="pwm")
        self.hal.pin("RIGHT_FWD", board_pin=9, mode="pwm")
        self.hal.pin("RIGHT_BWD", board_pin=10, mode="pwm")

        # Motor enable pins
        self.hal.pin("LEFT_EN",  board_pin=3, mode="output")
        self.hal.pin("RIGHT_EN", board_pin=11, mode="output")

        # Enable motors
        self.hal.write("LEFT_EN", 1)
        self.hal.write("RIGHT_EN", 1)

        self.left_speed = 0.0
        self.right_speed = 0.0

        self.subscribe("/robot/motor/cmd", self.on_cmd)

    def on_cmd(self, msg):
        self.left_speed  = msg.data.get("left", 0.0)
        self.right_speed = msg.data.get("right", 0.0)

    def tick(self):
        # Left motor
        if self.left_speed >= 0:
            self.hal.write("LEFT_FWD", abs(self.left_speed))
            self.hal.write("LEFT_BWD", 0)
        else:
            self.hal.write("LEFT_FWD", 0)
            self.hal.write("LEFT_BWD", abs(self.left_speed))

        # Right motor
        if self.right_speed >= 0:
            self.hal.write("RIGHT_FWD", abs(self.right_speed))
            self.hal.write("RIGHT_BWD", 0)
        else:
            self.hal.write("RIGHT_FWD", 0)
            self.hal.write("RIGHT_BWD", abs(self.right_speed))

    def on_emergency_stop(self, reason):
        for pin in ("LEFT_FWD", "LEFT_BWD", "RIGHT_FWD", "RIGHT_BWD"):
            self.hal.write(pin, 0)
        super().on_emergency_stop(reason)


robot = Robot("{project_name}")
robot.add_node(DriveNode("drive", hz=100, priority=NodePriority.HIGH))
robot.start()

# Demo: drive forward for 2s, turn, repeat
import time

robot.publish("motor/cmd", {{"left": 0.5, "right": 0.5}})
print("⏩ Moving forward...")
time.sleep(2)

robot.publish("motor/cmd", {{"left": 0.5, "right": -0.5}})
print("↩️ Turning...")
time.sleep(1)

robot.publish("motor/cmd", {{"left": 0, "right": 0}})
print("⏹ Stopped")

spin(robot)
''')


# ── 5. Servo Sweep ────────────────────────────────────────────────────────
_t("servo-sweep", "Servo Sweep", "Sweep a servo motor back and forth (0°–180°)", '''
"""
{project_name} — Servo Sweep
Generated by: neuros new {project_name} --template servo-sweep

Hardware: Standard hobby servo on PWM pin
"""
from neuros import Robot, spin
import math

robot = Robot("{project_name}")
robot.start()

robot.pin("SERVO", pin=9, mode="pwm")

angle = 0
direction = 1

@robot.every(hz=30)
def sweep():
    global angle, direction
    angle += direction * 3  # 3 degrees per step

    if angle >= 180:
        angle = 180
        direction = -1
    elif angle <= 0:
        angle = 0
        direction = 1

    # Convert angle to servo duty cycle (0.025 to 0.125 for standard servo)
    duty = 0.025 + (angle / 180.0) * 0.1
    robot.write("SERVO", duty)

    robot.publish("servo/position", {{"angle": angle, "duty": round(duty, 4)}})

print("🔄 Servo sweep running (0°–180°) — Ctrl+C to stop")
spin(robot)
''')


# ── 6. Motor Test ─────────────────────────────────────────────────────────
_t("motor-test", "Motor Test", "Test DC motor with acceleration ramps", '''
"""
{project_name} — Motor Test
Generated by: neuros new {project_name} --template motor-test

Ramps motor speed up and down to test motor driver wiring.
"""
from neuros import Robot, spin
import time

robot = Robot("{project_name}")
robot.start()

robot.pin("MOTOR", pin=5, mode="pwm")
robot.pin("MOTOR_DIR", pin=4, mode="output")

speed = 0.0
target = 1.0
ramp_rate = 0.02

@robot.every(hz=50)
def ramp():
    global speed, target
    if abs(speed - target) < ramp_rate:
        speed = target
        target = 0.0 if target > 0 else 1.0  # flip target
    elif speed < target:
        speed += ramp_rate
    else:
        speed -= ramp_rate

    robot.write("MOTOR", max(0, min(1, speed)))
    robot.publish("motor/test", {{"speed": round(speed, 3), "target": target}})

print("⚡ Motor test running — ramping up and down")
spin(robot)
''')


# ── 7. Sensor Reader ─────────────────────────────────────────────────────
_t("sensor-reader", "Sensor Reader", "Read and log multiple sensors in real-time", '''
"""
{project_name} — Sensor Reader
Generated by: neuros new {project_name} --template sensor-reader

Reads multiple sensors and publishes values to the Neural Bus.
View live data in the NEUROS Studio web UI.
"""
from neuros import Robot, spin

robot = Robot("{project_name}")
robot.start()

# Configure sensors (adjust pins for your board)
robot.pin("LIGHT",    pin=34, mode="analog_in")    # LDR / photoresistor
robot.pin("TEMP",     pin=35, mode="analog_in")    # TMP36 temperature
robot.pin("POT",      pin=36, mode="analog_in")    # Potentiometer
robot.pin("BUTTON",   pin=2,  mode="pullup")       # Push button
robot.pin("STATUS",   pin=13, mode="output")       # Status LED

tick_count = 0

@robot.every(hz=10)
def read_sensors():
    global tick_count
    tick_count += 1

    light  = robot.read("LIGHT")
    temp_v = robot.read("TEMP")
    pot    = robot.read("POT")
    button = robot.read("BUTTON")

    # Convert raw ADC to meaningful values
    temp_c = (temp_v * 3.3 - 0.5) * 100  # TMP36 formula

    # Publish to Neural Bus
    robot.publish("sensors/all", {{
        "light":      round(light, 3),
        "temperature": round(temp_c, 1),
        "potentiometer": round(pot, 3),
        "button":     int(button),
        "tick":       tick_count,
    }})

    # Blink status LED to show we're alive
    if tick_count % 10 == 0:
        robot.toggle("STATUS")

    # Print to terminal
    if tick_count % 50 == 0:
        print(f"  Light: {{light:.2f}} | Temp: {{temp_c:.1f}}°C | Pot: {{pot:.2f}} | Button: {{button}}")

print("📊 Sensor reader running — publishing to Neural Bus")
spin(robot)
''')


# ── 8. Remote Control ────────────────────────────────────────────────────
_t("remote-control", "Remote Control", "Control robot via keyboard input", '''
"""
{project_name} — Remote Control
Generated by: neuros new {project_name} --template remote-control

Control your robot with keyboard keys:
  W/S = forward/backward
  A/D = turn left/right
  Q   = quit
  X   = emergency stop
"""
from neuros import Robot, spin
import threading
import sys

robot = Robot("{project_name}")
robot.start()

robot.pin("MOTOR_L", pin=5, mode="pwm")
robot.pin("MOTOR_R", pin=6, mode="pwm")

speed = 0.5
current_cmd = "stop"

def keyboard_listener():
    global current_cmd
    print("\\n🎮 Remote Control Active")
    print("  W = Forward | S = Backward")
    print("  A = Left    | D = Right")
    print("  X = E-Stop  | Q = Quit\\n")

    while True:
        try:
            key = input("❯ ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            break

        if key == "w":
            current_cmd = "forward"
            robot.publish("motor/cmd", {{"left": speed, "right": speed}})
            print("  ⏩ Forward")
        elif key == "s":
            current_cmd = "backward"
            robot.publish("motor/cmd", {{"left": -speed, "right": -speed}})
            print("  ⏪ Backward")
        elif key == "a":
            current_cmd = "left"
            robot.publish("motor/cmd", {{"left": -speed, "right": speed}})
            print("  ↩️ Left")
        elif key == "d":
            current_cmd = "right"
            robot.publish("motor/cmd", {{"left": speed, "right": -speed}})
            print("  ↪️ Right")
        elif key == "" or key == " ":
            current_cmd = "stop"
            robot.publish("motor/cmd", {{"left": 0, "right": 0}})
            print("  ⏹ Stop")
        elif key == "x":
            print("  🛑 EMERGENCY STOP")
            robot.stop()
            break
        elif key == "q":
            print("  👋 Quitting")
            robot.stop()
            sys.exit(0)

# Run keyboard listener in a thread
t = threading.Thread(target=keyboard_listener, daemon=True)
t.start()

spin(robot)
''')


# ── 9. Light Follower ────────────────────────────────────────────────────
_t("light-follower", "Light Follower", "Follow a light source using LDR photoresistors", '''
"""
{project_name} — Light Follower
Generated by: neuros new {project_name} --template light-follower

Hardware:
  - 2x LDR (Light Dependent Resistor) — left and right
  - 2x DC motors
  - Motor driver
"""
from neuros import Robot, Node, spin, NodePriority


class LightFollowerNode(Node):
    """Follow the brightest light source using differential drive."""

    def configure(self):
        self.hal.pin("LDR_LEFT",  board_pin=34, mode="analog_in")
        self.hal.pin("LDR_RIGHT", board_pin=35, mode="analog_in")
        self.hal.pin("MOTOR_L",   board_pin=5,  mode="pwm")
        self.hal.pin("MOTOR_R",   board_pin=6,  mode="pwm")

        self.base_speed = 0.4
        self.gain = 2.0
        self.threshold = 0.1  # minimum light to activate

    def tick(self):
        left_light  = self.hal.read("LDR_LEFT")
        right_light = self.hal.read("LDR_RIGHT")

        avg_light = (left_light + right_light) / 2

        if avg_light < self.threshold:
            # Too dark — stop
            self.hal.write("MOTOR_L", 0)
            self.hal.write("MOTOR_R", 0)
            return

        # Differential: steer towards brighter side
        error = left_light - right_light
        left_speed  = max(0, min(1, self.base_speed + error * self.gain))
        right_speed = max(0, min(1, self.base_speed - error * self.gain))

        self.hal.write("MOTOR_L", left_speed)
        self.hal.write("MOTOR_R", right_speed)

        self.publish("/robot/light", {{
            "left": round(left_light, 3),
            "right": round(right_light, 3),
            "error": round(error, 3),
        }})

    def on_emergency_stop(self, reason):
        self.hal.write("MOTOR_L", 0)
        self.hal.write("MOTOR_R", 0)
        super().on_emergency_stop(reason)


robot = Robot("{project_name}")
robot.add_node(LightFollowerNode("light_follower", hz=20, priority=NodePriority.HIGH))
robot.start()

print("💡 Light follower running — shine a flashlight to steer the robot")
spin(robot)
''')


# ── 10. Node Example ─────────────────────────────────────────────────────
_t("node-example", "Custom Node", "Example showing Node lifecycle, pub/sub, and HAL usage", '''
"""
{project_name} — Custom Node Example
Generated by: neuros new {project_name} --template node-example

Demonstrates the full Node lifecycle:
  configure() → on_activate() → tick() → destroy()
"""
from neuros import Robot, Node, spin, NodePriority
import logging


class BlinkerNode(Node):
    """Blinks an LED at a configurable rate."""

    def configure(self):
        self.hal.pin("LED", board_pin=13, mode="output")
        self.led_state = False
        self.logger = logging.getLogger(self.name)

    def on_activate(self):
        self.logger.info("BlinkerNode activated at %.1f Hz", self.hz)

    def tick(self):
        self.led_state = not self.led_state
        self.hal.write("LED", int(self.led_state))
        self.publish("/robot/actuator/led", {{"state": self.led_state}})

    def destroy(self):
        self.hal.write("LED", 0)  # turn off LED on shutdown
        super().destroy()


class StatusNode(Node):
    """Publishes system status and listens for LED events."""

    def configure(self):
        self.counter = 0
        self.led_toggles = 0
        self.subscribe("/robot/actuator/led", self.on_led)

    def on_led(self, msg):
        self.led_toggles += 1

    def tick(self):
        self.counter += 1
        self.publish("/robot/system/status", {{
            "uptime_ticks": self.counter,
            "led_toggles": self.led_toggles,
            "node_state": self.state.value,
        }})

        if self.counter % 50 == 0:
            print(f"  Status: tick={{self.counter}} led_toggles={{self.led_toggles}}")


# Create robot with multiple nodes
robot = Robot("{project_name}")
robot.add_node(BlinkerNode("blinker", hz=2, priority=NodePriority.NORMAL))
robot.add_node(StatusNode("status", hz=0.2, priority=NodePriority.LOW))
robot.start()

print("🧩 Custom node example running — 2 nodes active")
spin(robot)
''')


def get_template(name: str) -> Optional[dict]:
    """Get a template by name."""
    # Normalize: accept both "line-follower" and "line_follower"
    normalized = name.lower().replace("_", "-")
    return TEMPLATES.get(normalized)


def list_templates() -> List[dict]:
    """Return all available templates."""
    return list(TEMPLATES.values())


def render_template(template_name: str, project_name: str) -> Optional[str]:
    """Render a template with the project name substituted."""
    tmpl = get_template(template_name)
    if tmpl is None:
        return None
    return tmpl["code"].format(project_name=project_name)
