"""
neuros.cli
==========
NEUROS OS Command Line Interface — Phase 1.

Commands
--------
    neuros init <name>          Create a new robot project
    neuros run <file.py>        Run a robot script
    neuros status               Show kernel / bus status
    neuros flash --board=...    Flash firmware to Arduino
    neuros version              Show version info
    neuros doctor               Check system requirements

Install (after `pip install neuros`):
    neuros --help
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import textwrap
from pathlib import Path

# ── Template: new robot project ───────────────────────────────────────────
_TEMPLATE_BASIC = '''\
"""
{name} — NEUROS OS Robot  (Phase 1 / Domain A)
Generated by: neuros init {name}
"""
from neuros import Robot, spin

robot = Robot(name="{name}", board="simulator")
robot.start()

# Configure pins (change pin numbers for your board)
robot.pin("LED", pin=13, mode="output")

# This runs at 1 Hz — toggle the LED every second
@robot.every(hz=1)
def blink():
    robot.toggle("LED")
    robot.publish("actuator/led", {{"state": "toggle"}})

# Subscribe to any message for logging
def on_message(msg):
    print(f"  {{msg.topic}}: {{msg.data}}")

robot.subscribe("#", on_message)

# Block forever — Ctrl+C to stop
spin(robot)
'''

_TEMPLATE_NODE = '''\
"""
{name} — NEUROS OS Robot with custom Nodes  (Phase 1 / Domain A)
Generated by: neuros init {name} --template=node
"""
from neuros import Robot, Node, spin, NodePriority


class BlinkerNode(Node):
    """Blinks an LED at a configurable rate."""

    def configure(self):
        self.hal.pin("LED", board_pin=13, mode="output")
        self.led_state = False
        self.logger = __import__("logging").getLogger(self.name)

    def on_activate(self):
        self.logger.info("BlinkerNode activated at %.1f Hz", self.hz)

    def tick(self):
        self.led_state = not self.led_state
        self.hal.write("LED", int(self.led_state))
        self.publish("/robot/actuator/led", {{"state": self.led_state}})

    def destroy(self):
        self.hal.write("LED", 0)
        super().destroy()


class StatusNode(Node):
    """Prints robot status every 5 seconds."""

    def configure(self):
        self.counter = 0

    def tick(self):
        self.counter += 1
        self.publish("/robot/system/tick", {{"count": self.counter}})


robot = Robot(name="{name}", board="simulator")
robot.add_node(BlinkerNode("blinker", hz=2, priority=NodePriority.NORMAL))
robot.add_node(StatusNode("status",  hz=0.2))
robot.start()
spin(robot)
'''


# ── CLI commands ───────────────────────────────────────────────────────────
def cmd_init(args: argparse.Namespace) -> None:
    name     = args.name
    template = getattr(args, "template", "basic")
    outdir   = Path(name)

    if outdir.exists():
        print(f"ERROR: directory '{name}' already exists.")
        sys.exit(1)

    outdir.mkdir()

    if template == "node":
        code = _TEMPLATE_NODE.format(name=name)
        fname = "robot_node.py"
    else:
        code = _TEMPLATE_BASIC.format(name=name)
        fname = "robot.py"

    (outdir / fname).write_text(code)
    (outdir / "requirements.txt").write_text("neuros>=0.1.0\n")
    (outdir / ".neuros").write_text(f"name={name}\nversion=0.1.0\ndomain=A\n")

    print(f"""
✅ NEUROS project created: {name}/
   {fname}          ← your robot code
   requirements.txt   ← dependencies
   .neuros            ← project config

Next steps:
   cd {name}
   python {fname}
""")


def cmd_run(args: argparse.Namespace) -> None:
    path = Path(args.file)
    if not path.exists():
        print(f"ERROR: file not found: {args.file}")
        sys.exit(1)
    import runpy
    runpy.run_path(str(path), run_name="__main__")


def cmd_status(args: argparse.Namespace) -> None:
    # In a real implementation this would connect to a running robot daemon.
    # Phase 1: just show system info.
    import platform
    import importlib.metadata as meta

    try:
        ver = meta.version("neuros")
    except Exception:
        ver = "0.1.0-dev"

    print(f"""
NEUROS OS Status
────────────────
  Version  : {ver}
  Phase    : 1 — Basic Robot Support (Domain A)
  Python   : {sys.version.split()[0]}
  Platform : {platform.system()} {platform.machine()}

Domains ready
  ✅ Domain A — Zephyr / Arduino / Simulator
  🔲 Domain B — Linux RT / ROS2     [Phase 2]
  🔲 Domain C — QNX Certified       [Phase 4]

HAL drivers available
  ✅ SimulatorHAL   (always available)
  ⚡ ArduinoHAL     (requires pyserial + firmware)
  🔲 RaspberryPiHAL [Phase 2]

Run 'neuros doctor' for a full system check.
""")


def cmd_version(args: argparse.Namespace) -> None:
    print("NEUROS OS v0.1.0-phase1 | Domain A | 'One OS. Every Robot.'")


def cmd_doctor(args: argparse.Namespace) -> None:
    print("NEUROS Doctor — checking system requirements...\n")
    checks = [
        ("Python ≥ 3.9",    sys.version_info >= (3, 9)),
        ("pyserial",        _can_import("serial")),
        ("numpy",           _can_import("numpy")),
        ("RPi.GPIO",        _can_import("RPi.GPIO")),
    ]
    for label, ok in checks:
        mark = "✅" if ok else "❌"
        print(f"  {mark}  {label}")
    print()


def _can_import(name: str) -> bool:
    try:
        __import__(name)
        return True
    except ImportError:
        return False


# ── Entry point ────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser(
        prog="neuros",
        description="NEUROS OS — One OS. Every Robot.",
    )
    sub = parser.add_subparsers(dest="command")

    # init
    p_init = sub.add_parser("init", help="Create a new robot project")
    p_init.add_argument("name", help="Project name")
    p_init.add_argument("--template", choices=["basic", "node"], default="basic")

    # run
    p_run = sub.add_parser("run", help="Run a robot script")
    p_run.add_argument("file", help="Path to robot Python file")

    # status
    sub.add_parser("status",  help="Show NEUROS status")
    sub.add_parser("version", help="Show version")
    sub.add_parser("doctor",  help="Check system requirements")

    args = parser.parse_args()

    commands = {
        "init":    cmd_init,
        "run":     cmd_run,
        "status":  cmd_status,
        "version": cmd_version,
        "doctor":  cmd_doctor,
    }
    fn = commands.get(args.command)
    if fn:
        fn(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
